//! D015 acceptance (Linux): the differential suite. The SAME
//! perturbation — touching a source file's mtime without changing its
//! content — makes the mtime lane rebuild and the checksum lane stay
//! fresh; a REAL content change rebuilds in both lanes. Runs the real
//! nightly Cargo inside the canonical namespace.
//!
//! Executes real `bwrap` namespaces; skips loudly when unsupported.
#![cfg(target_os = "linux")]

use rabs_sandbox::canonical_mounts::{CanonicalMountPlan, UnitMount};
use rabs_sandbox::canonical_namespace::{HostIsolationSupport, build_canonical_argv, command_for};
use rabs_sandbox::layout;

fn supported() -> Option<HostIsolationSupport> {
    let support = HostIsolationSupport::probe();
    if support.missing_for_canonical().is_empty() {
        Some(support)
    } else {
        eprintln!(
            "SKIP: host cannot run D015 acceptance; missing {:?}",
            support.missing_for_canonical()
        );
        None
    }
}

fn toolchain_dir() -> std::path::PathBuf {
    let cargo_path = std::env::var("CARGO").expect("cargo sets $CARGO for tests");
    std::path::Path::new(&cargo_path)
        .parent()
        .and_then(std::path::Path::parent)
        .expect("<root>/bin/cargo")
        .to_path_buf()
}

fn write(root: &std::path::Path, rel: &str, contents: &str) {
    let path = root.join(rel);
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(path, contents).unwrap();
}

fn fixture(root: &std::path::Path) {
    write(
        root,
        "Cargo.toml",
        "[package]\nname = \"rabs-d015\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[workspace]\n",
    );
    write(root, "src/main.rs", "fn main() {}\n");
    write(
        root,
        "Cargo.lock",
        "# This file is automatically @generated by Cargo.\n\
         # It is not intended for manual editing.\n\
         version = 4\n\n\
         [[package]]\n\
         name = \"rabs-d015\"\n\
         version = \"0.1.0\"\n",
    );
}

/// Build in the namespace; `checksum_lane` adds `-Zchecksum-freshness`.
fn build(
    support: &HostIsolationSupport,
    source: &std::path::Path,
    out_backing: &std::path::Path,
    cargo_home: &std::path::Path,
    checksum_lane: bool,
) -> String {
    let home = tempfile::tempdir().unwrap();
    let mut plan = CanonicalMountPlan::new(toolchain_dir(), source, cargo_home, home.path());
    plan.out_units.push(UnitMount {
        unit: "fixture".into(),
        backing: out_backing.to_path_buf(),
    });
    plan.extra_env.push((
        "CARGO_TARGET_DIR".into(),
        format!("{}/fixture", layout::OUT),
    ));
    let mut args = vec!["build".to_string(), "--offline".to_string()];
    if checksum_lane {
        args.push("-Zchecksum-freshness".to_string());
    }
    let spec = plan.to_spec().unwrap();
    let launch = build_canonical_argv(&spec, support, "cargo", &args).unwrap();
    let out = command_for(&launch).output().unwrap();
    let stderr = String::from_utf8_lossy(&out.stderr).into_owned();
    assert!(out.status.success(), "build failed:\n{stderr}");
    stderr
}

/// Touch a file's mtime to now WITHOUT changing content.
fn touch(path: &std::path::Path) {
    std::fs::File::options()
        .write(true)
        .open(path)
        .unwrap()
        .set_modified(std::time::SystemTime::now())
        .unwrap();
}

/// ACCEPTANCE: the mtime-vs-checksum differential on hits/rebuilds.
#[test]
fn touch_rebuilds_mtime_lane_but_not_checksum_lane() {
    let Some(support) = supported() else { return };

    for (lane, expect_rebuild_on_touch) in [(false, true), (true, false)] {
        let source = tempfile::tempdir().unwrap();
        fixture(source.path());
        let out_backing = tempfile::tempdir().unwrap();
        let cargo_home = tempfile::tempdir().unwrap();

        let first = build(
            &support,
            source.path(),
            out_backing.path(),
            cargo_home.path(),
            lane,
        );
        assert!(first.contains("Compiling"), "lane {lane}: control compiles");

        // The differential perturbation: mtime bump, content identical.
        std::thread::sleep(std::time::Duration::from_millis(20));
        touch(&source.path().join("src/main.rs"));
        let after_touch = build(
            &support,
            source.path(),
            out_backing.path(),
            cargo_home.path(),
            lane,
        );
        assert_eq!(
            after_touch.contains("Compiling"),
            expect_rebuild_on_touch,
            "lane checksum={lane}: touch-without-change behavior:\n{after_touch}"
        );

        // A REAL content change rebuilds in BOTH lanes.
        write(source.path(), "src/main.rs", "fn main() { let _x = 1; }\n");
        let after_change = build(
            &support,
            source.path(),
            out_backing.path(),
            cargo_home.path(),
            lane,
        );
        assert!(
            after_change.contains("Compiling"),
            "lane checksum={lane}: content change must rebuild:\n{after_change}"
        );
    }
}
